#%RAML 0.8
title: microrest.php Example API
baseUri: http://mr.lh/api
mediaType: application/json
/users:
  displayName: Users
  get:
    description: Retrieves one or more users.
    responses:
      200:
  post:
    description: Creates one or more users.
    responses:
      200:
  /{id}:
    get:
      description: Retrieves one user.
      responses:
        200:
        402:
            body:
                application/json:
                    schema: 
    put:
      description: Updates one user.
      responses:
        200:
    delete:
      description: Delete one user.